# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# You can update your hooks to the latest version automatically by running `pre-commit autoupdate`

repos:
  # Some out-of-the-box hooks for pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key

  # Find security vulnerabilities, compliance issues, and infrastructure misconfigurations early in the development cycle of your infrastructure-as-code with KICS by Checkmarx.
  # KICS stands for Keeping Infrastructure as Code Secure, it is open source and is a must-have for any cloud native project.
  # https://docs.kics.io/latest/commands/
  # Ignoring errors: https://docs.kics.io/latest/running-kics/#using_commands_on_scanned_files_as_comments
  - repo: https://github.com/Checkmarx/kics
    rev: v2.1.3
    hooks:
      - id: kics-scan
        # TODO solve the high severity issues first
        args: ["--exclude-severities", "info,low,medium"]
        pass_filenames: false
        always_run: true

  # Gitleaks is a SAST tool for detecting and preventing hardcoded secrets like passwords, api keys, and tokens in git repos.
  # Gitleaks is an easy-to-use, all-in-one solution for detecting secrets, past or present, in your code.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks

  # ShellCheck, a static analysis tool for shell scripts - https://www.shellcheck.net/
  # Ignoring errors: https://www.shellcheck.net/wiki/Ignore, `.shellcheckrc`
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # flake8 is a python tool that glues together pycodestyle, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.
  # Third-party scripts are excluded.
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  # Dockerfile linter, validate inline bash, written in Haskell
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        exclude: "\\.dockerignore$"
